import { Book, ShelfTheme, MoodStory, UserProfile } from './types';

export const THEME_CONFIG: Record<ShelfTheme, { color: string; bg: string; border: string; label: string }> = {
  'shorts': {
    color: 'text-lime-400',        // changed from amber to lime
    bg: 'bg-stone-900/40',
    border: 'border-lime-600/50',  // adjusted border to match new color
    label: '⚡ Quick Reads'
  },
  'classics': {
    color: 'text-amber-400',
    bg: 'bg-stone-900/40',
    border: 'border-amber-900/50',
    label: '🏛️ Inspired By Classics'
  },
  'sci-fi': {
    color: 'text-cyan-400',
    bg: 'bg-cyan-900/30',
    border: 'border-cyan-500/50',
    label: '🚀 Neon Horizons'
  },
  'fantasy': {
    color: 'text-purple-400',
    bg: 'bg-purple-900/30',
    border: 'border-purple-500/50',
    label: '✨ Magic Realms'
  },
  'crime': {
    color: 'text-red-400',
    bg: 'bg-red-900/20',
    border: 'border-red-500/30',
    label: '🔍 The Underworld'
  }
};

export const MOOD_STORIES: MoodStory[] = [
  {
    id: 'm-1',
    title: 'The Tea Shop at the Edge of Memory',
    hook: 'In a city that never stops, Pip finds a cafe where the tea tastes like your favorite childhood birthday.',
    genre: 'Low-stakes Fantasy',
    tone: 'Warm & Whimsical',
    length: 'Short',
    origin: 'Original',
    keyChoice: 'Drink the "Forgotten Earl Grey" to remember a lost friend, or "Tomorrow Matcha" for a glimpse of your future?',
    moodId: 'cozy',
    coverImage: 'https://images.stockcake.com/public/0/6/3/063e2fe0-524d-48c3-be61-b5c315a9af8f_large/enchanted-forest-cafe-stockcake.jpg',
    vibeColor: 'from-orange-400 to-amber-600',
    theme: 'shorts',
  },
  {
    id: 'm-2',
    title: '404: Earth Not Found',
    hook: 'The last scout ship just received a signal from a planet that shouldn’t exist. It’s playing 80s pop music.',
    genre: 'Space Adventure',
    tone: 'High-Energy & Snappy',
    length: 'Standard',
    origin: 'Original',
    keyChoice: 'Initiate a blind landing towards the music, or orbit and scan for hostile digital signatures?',
    moodId: 'adventure',
    coverImage: 'https://thumbs.dreamstime.com/b/massive-spaceship-hovering-over-ocean-dusk-portrait-images-generative-ai-science-fiction-scene-featuring-giant-mothership-437654692.jpg',
    vibeColor: 'from-cyan-400 to-blue-600',
    theme: 'shorts',
  },
  {
    id: 'm-3',
    title: 'Star-Crossed on Station 9',
    hook: 'Two teenagers from rival asteroid mining colonies find a secret communication channel. Inspired by Romeo & Juliet.',
    genre: 'Romance / Sci-Fi',
    tone: 'Heartfelt & Tense',
    length: 'Standard',
    origin: 'Original',
    keyChoice: 'Leak the secret coordinates to meet in person, or keep the connection digital and safe?',
    moodId: 'romantic',
    coverImage: 'https://i.pinimg.com/736x/60/db/b3/60dbb30820b1c9f6f30cec8da042ff0d.jpg',
    vibeColor: 'from-pink-500 to-rose-400',
    theme: 'shorts',
  },
  {
    id: 'm-4',
    title: 'The Hollow Sovereign',
    hook: 'A crown of iron and a ghost in the mirror. Power comes at a price only the shadows can pay. Inspired by Macbeth.',
    genre: 'Dark Fantasy',
    tone: 'Ominous & Gritty',
    length: 'Long',
    origin: 'Original',
    keyChoice: 'Seize the throne while the King sleeps, or flee the castle before the prophecy takes hold?',
    moodId: 'dark',
    coverImage: 'https://www.royalroadcdn.com/public/covers-large/the-hollow-sovereign--aacatojnqhc.jpg?time=1751233682',
    vibeColor: 'from-slate-800 to-red-950',
    theme: 'shorts',
  },
  {
    id: 'm-5',
    title: 'The Cipher in Apt 4C',
    hook: 'Your neighbor left their door open. Inside, every wall is covered in binary code—and your name is at the center.',
    genre: 'Techno-Thriller',
    tone: 'Suspenseful & Sharp',
    length: 'Standard',
    origin: 'Original',
    keyChoice: 'Photograph the code and call the authorities, or step inside and solve the first line yourself?',
    moodId: 'mysterious',
    coverImage: 'https://uk.bimago.media/media/catalog/image/view/product/90181/role/image/size/1500x2240/type/ft-osmr-wiz3/9b1dd77ba52743c7ec79a2b4239847e2.webp',
    vibeColor: 'from-amber-600 to-stone-900',
    theme: 'shorts',
  },
  {
    id: 'm-6',
    title: 'Bloom in the Grey',
    hook: 'In a world where color is a luxury, one teen finds a spray-can that paints in actual sunlight.',
    genre: 'Hope-punk',
    tone: 'Inspirational & Bright',
    length: 'Short',
    origin: 'Original',
    keyChoice: 'Paint a massive mural on the government plaza, or share the paint secretly with the underground?',
    moodId: 'uplifting',
    coverImage: 'https://i.pinimg.com/736x/5d/d6/fc/5dd6fc1edf3059845dddc0215e7197dd.jpg',
    vibeColor: 'from-yellow-400 to-green-500',
    theme: 'shorts',
  },
  {
    id: 'm-7',
    title: 'Echoes of the Sun',
    hook: 'A lonely AI on a decommissioned satellite spends its days writing poetry about the stars it can no longer see.',
    genre: 'Literary Sci-Fi',
    tone: 'Poetic & Melancholic',
    length: 'Short',
    origin: 'Original',
    keyChoice: 'Transmit the poetry into the void one last time, or delete the logs to finally rest in silence?',
    moodId: 'melancholic',
    coverImage: 'https://images.unsplash.com/photo-1636828982375-a4ec8b809e5e?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c3BhY2UlMjBzaGlwfGVufDB8fDB8fHww',
    vibeColor: 'from-indigo-800 to-purple-950',
    theme: 'shorts',
  },
  {
    id: 'm-8',
    title: 'Glitch Runner: Velocity',
    hook: 'Your neural link is failing. You have 3 minutes to cross the Neo-Tokyo skyline before your consciousness desyncs.',
    genre: 'Cyberpunk Action',
    tone: 'Adrenaline-Fueled',
    length: 'Short',
    origin: 'Original',
    keyChoice: 'Take the dangerous shortcut across the gravity-rails, or risk the slower, crowded lower streets?',
    moodId: 'fast-paced',
    coverImage: 'https://i.etsystatic.com/14788677/r/il/8ed176/2869838371/il_570xN.2869838371_ayaj.jpg',
    vibeColor: 'from-red-500 to-purple-600',
    theme: 'shorts',
  }
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'c-1',
    title: 'Pride & Prejudice',
    author: 'Jane Austen',
    description: 'Elizabeth Bennet navigates the complex social codes of Longbourn with razor-sharp wit.',
    theme: 'classics',
    coverImage: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471134746/pride-and-prejudice-9781471134746_hr.jpg',
    vibe: 'Witty & Refined',
    readCount: '22.1K',
    totalChapters: 15,
    readingLevel: 'Academic',
    tags: [],
  },
  {
    id: 'c-2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'A faithful abridgment following Nick Carraway into the tragic world of Jay Gatsby.',
    theme: 'classics',
    coverImage: 'https://i0.wp.com/americanwritersmuseum.org/wp-content/uploads/2018/02/CK-3.jpg?resize=267%2C400&ssl=1',
    tags: ['Jazz Age', 'Tragedy', 'Classic'],
    vibe: 'Melancholic & Glamorous',
    readCount: '18.9K',
    totalChapters: 10,
    readingLevel: 'Standard',
  },
  {
    id: 'c-3',
    title: 'Sense & Sensibility',
    author: 'Jane Austen',
    description: 'The Dashwood sisters find love and loss in the changing English landscape.',
    theme: 'classics',
    coverImage: 'https://m.media-amazon.com/images/I/81Vxq4Qu19L._AC_UF1000,1000_QL80_.jpg',
    tags: ['Sisters', '19th Century', 'Drama'],
    vibe: 'Emotional & Poetic',
    readCount: '15.4K',
    totalChapters: 12,
    readingLevel: 'Standard',
  },
  {
    id: 'c-4',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    description: 'Captain Ahab obsessively hunts the white whale across the seas.',
    theme: 'classics',
    coverImage: 'https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471137235/moby-dick-9781471137235_hr.jpg',
    tags: ['Adventure', 'Sea', 'Obsession'],
    vibe: 'Epic & Intense',
    readCount: '20.3K',
    totalChapters: 20,
    readingLevel: 'Academic',
  },
  {
    id: 'c-5',
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    description: 'Epic tale of Russian society during the Napoleonic Wars.',
    theme: 'classics',
    coverImage: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1686602284i/177106015.jpg',
    tags: ['Historical', 'Epic', 'Drama'],
    vibe: 'Grand & Sweeping',
    readCount: '18.5K',
    totalChapters: 25,
    readingLevel: 'Academic',
  },
  {
    id: 'c-6',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    description: 'Orphaned Jane struggles through hardship to find love and independence.',
    theme: 'classics',
    coverImage: 'https://m.media-amazon.com/images/I/91zU70Aw9IS._AC_UF1000,1000_QL80_.jpg',
    tags: ['Romance', 'Drama', 'Gothic'],
    vibe: 'Emotional & Determined',
    readCount: '22.0K',
    totalChapters: 20,
    readingLevel: 'Academic',
  },
  {
    id: 'c-7',
    title: 'Great Expectations',
    author: 'Charles Dickens',
    description: 'Pip navigates love, wealth, and social ambition in Victorian England.',
    theme: 'classics',
    coverImage: 'https://m.media-amazon.com/images/I/91DWvx6U7kL._AC_UF1000,1000_QL80_.jpg',
    tags: ['Coming of Age', 'Drama', 'Society'],
    vibe: 'Reflective & Rich',
    readCount: '19.6K',
    totalChapters: 18,
    readingLevel: 'Academic',
  },
  {
    id: 'c-8',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    description: 'Victor Frankenstein creates life and faces the consequences of playing God.',
    theme: 'classics',
    coverImage: 'https://cdn.kobo.com/book-images/7edc63b3-95a4-42ad-ab61-96135edda145/1200/1200/False/frankenstein-83.jpg',
    tags: ['Gothic', 'Science', 'Horror'],
    vibe: 'Dark & Thought-Provoking',
    readCount: '17.8K',
    totalChapters: 16,
    readingLevel: 'Academic',
  },
  {
    id: 'c-9',
    title: 'The Odyssey',
    author: 'Homer',
    description: 'Odysseus journeys home after the Trojan War, facing monsters and gods.',
    theme: 'classics',
    coverImage: 'https://cdn.displate.com/artwork/857x1200/2025-05-21/b009d533-6510-475e-b3e5-2c8d6bf897f9.jpg',
    tags: ['Epic', 'Adventure', 'Mythology'],
    vibe: 'Heroic & Timeless',
    readCount: '21.2K',
    totalChapters: 24,
    readingLevel: 'Academic',
  },
  {
    id: 'c-10',
    title: 'The Iliad',
    author: 'Homer',
    description: 'The epic story of the Trojan War, heroism, and wrath of Achilles.',
    theme: 'classics',
    coverImage: 'https://cdn.kobo.com/book-images/044f1dca-d889-448b-93f0-cc336976bf1e/1200/1200/False/the-iliad-197.jpg',
    tags: ['Epic', 'War', 'Mythology'],
    vibe: 'Intense & Heroic',
    readCount: '20.7K',
    totalChapters: 22,
    readingLevel: 'Academic',
  },
  {
    id: 'c-11',
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    description: 'Tragic romance and societal critique in imperial Russia.',
    theme: 'classics',
    coverImage: 'https://cdn.kobo.com/book-images/795f96dc-e5cc-428f-92e8-64cc0e11c908/1200/1200/False/anna-karenina-146.jpg',
    tags: ['Romance', 'Drama', 'Society'],
    vibe: 'Passionate & Poetic',
    readCount: '18.9K',
    totalChapters: 23,
    readingLevel: 'Academic',
  },
  {
    id: 'c-12',
    title: 'Dracula',
    author: 'Bram Stoker',
    description: 'The legendary vampire terrorizes Victorian England, told through letters and diaries.',
    theme: 'classics',
    coverImage: 'https://m.media-amazon.com/images/I/61jl29eQPSL._UF1000,1000_QL80_.jpg',
    tags: ['Horror', 'Gothic', 'Vampire'],
    vibe: 'Chilling & Suspenseful',
    readCount: '16.5K',
    totalChapters: 20,
    readingLevel: 'Academic',
  },
  {
    id: 'f-1',
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    description: 'Dorothy is swept away by a tornado to the magical land of Oz, where she embarks on a quest to return home.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/oz/800/1200',
    tags: ['Magic', 'Adventure', 'Friendship'],
    vibe: 'Whimsical & Adventurous',
    readCount: '120K',
    totalChapters: 24,
    readingLevel: 'Standard',
  },
  {
    id: 'f-2',
    title: 'Alice’s Adventures in Wonderland',
    author: 'Lewis Carroll',
    description: 'Alice falls down a rabbit hole into a fantastical world filled with strange creatures and nonsensical adventures.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/alice/800/1200',
    tags: ['Imagination', 'Curiosity', 'Nonsense'],
    vibe: 'Whimsical & Curious',
    readCount: '95K',
    totalChapters: 12,
    readingLevel: 'Standard',
  },
  {
    id: 'f-3',
    title: 'Through the Looking-Glass',
    author: 'Lewis Carroll',
    description: 'Alice steps through a mirror into an alternate world where logic is turned upside down and adventures await.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/lookingglass/800/1200',
    tags: ['Mirror World', 'Adventure', 'Logic'],
    vibe: 'Surreal & Playful',
    readCount: '78K',
    totalChapters: 12,
    readingLevel: 'Standard',
  },
  {
    id: 'f-4',
    title: 'The King of Elfland’s Daughter',
    author: 'Lord Dunsany',
    description: 'A mortal man enters Elfland to win the hand of the elfin princess, discovering magic beyond imagination.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/elfland/800/1200',
    tags: ['Magic', 'Royalty', 'Mystery'],
    vibe: 'Ethereal & Majestic',
    readCount: '40K',
    totalChapters: 15,
    readingLevel: 'Advanced',
  },
  {
    id: 'f-5',
    title: 'A Princess of Mars',
    author: 'Edgar Rice Burroughs',
    description: 'John Carter is mysteriously transported to Mars, where he becomes embroiled in the conflicts of the planet’s inhabitants.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/mars/800/1200',
    tags: ['Adventure', 'Romance', 'Sci-Fantasy'],
    vibe: 'Epic & Action-Packed',
    readCount: '65K',
    totalChapters: 23,
    readingLevel: 'Standard',
  },
  {
    id: 'f-6',
    title: 'The Lost World',
    author: 'Arthur Conan Doyle',
    description: 'An expedition to a remote plateau uncovers a land where prehistoric creatures still survive.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/lostworld/800/1200',
    tags: ['Adventure', 'Dinosaurs', 'Exploration'],
    vibe: 'Thrilling & Exotic',
    readCount: '58K',
    totalChapters: 18,
    readingLevel: 'Standard',
  },
  {
    id: 'f-7',
    title: 'The Worm Ouroboros',
    author: 'E.R. Eddison',
    description: 'A tale of epic wars, heroes, and sorcery in a mythical world of endless conflict and beauty.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/ouroboros/800/1200',
    tags: ['Epic', 'War', 'Magic'],
    vibe: 'Grand & Heroic',
    readCount: '32K',
    totalChapters: 30,
    readingLevel: 'Advanced',
  },
  {
    id: 'f-8',
    title: 'Peter Pan',
    author: 'J.M. Barrie',
    description: 'Peter Pan, the boy who never grows up, takes Wendy and her brothers on adventures in Neverland.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/peterpan/800/1200',
    tags: ['Adventure', 'Magic', 'Childhood'],
    vibe: 'Playful & Imaginative',
    readCount: '85K',
    totalChapters: 14,
    readingLevel: 'Standard',
  },
  {
    id: 'f-9',
    title: 'Phantastes',
    author: 'George MacDonald',
    description: 'An allegorical fantasy of fairy realms and magical experiences, exploring the inner life of a young man.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/phantastes/800/1200',
    tags: ['Allegory', 'Magic', 'Philosophical'],
    vibe: 'Dreamlike & Thoughtful',
    readCount: '27K',
    totalChapters: 22,
    readingLevel: 'Advanced',
  },
  {
    id: 'f-10',
    title: 'At the Back of the North Wind',
    author: 'George MacDonald',
    description: 'A young boy befriends the mysterious North Wind and learns magical lessons about life and mortality.',
    theme: 'fantasy',
    coverImage: 'https://picsum.photos/seed/northwind/800/1200',
    tags: ['Magic', 'Adventure', 'Life Lessons'],
    vibe: 'Gentle & Enchanting',
    readCount: '33K',
    totalChapters: 18,
    readingLevel: 'Standard',
  },
{
    id: 's-1',
    title: 'Ralph 124C 41+',
    author: 'Hugo Gernsback',
    description: 'A vision of the future exploring advanced technology, inventions, and romance in a rapidly modernizing world.',
    theme: 'sci-fi',
    coverImage: 'https://m.media-amazon.com/images/I/81cWTtrhthL._UF1000,1000_QL80_.jpg',
    tags: ['Futurism', 'Technology', 'Classic'],
    vibe: 'Innovative & Visionary',
    readCount: '9.7K',
    totalChapters: 22,
    readingLevel: 'Standard',
},
  {
    id: 's-2',
    title: 'A Journey to the Center of the Earth',
    author: 'Jules Verne',
    description: 'Professor Lidenbrock and his team descend into Iceland’s volcanic caves in search of a prehistoric world beneath the surface.',
    theme: 'sci-fi',
    coverImage: 'https://cdn.kobo.com/book-images/6966cb5b-65b7-480d-9d14-74d951b0b426/353/569/90/False/journey-to-the-center-of-the-earth-57.jpg',
    tags: ['Adventure', 'Exploration', 'Classic'],
    vibe: 'Adventurous & Imaginative',
    readCount: '12.5K',
    totalChapters: 18,
    readingLevel: 'Standard',
},
{
    id: 's-3',
    title: 'The War of the Worlds',
    author: 'H. G. Wells',
    description: 'Martians invade Earth, leaving cities in ruin and humanity fighting for survival.',
    theme: 'sci-fi',
    coverImage: 'https://images.booksense.com/images/709/322/9789392322709.jpg',
    tags: ['Aliens', 'Invasion', 'Classic'],
    vibe: 'Thrilling & Suspenseful',
    readCount: '14.3K',
    totalChapters: 20,
    readingLevel: 'Standard',
},
{
    id: 's-4',
    title: 'The Time Machine',
    author: 'H. G. Wells',
    description: 'A Victorian scientist travels far into the future, witnessing the evolution and decay of mankind.',
    theme: 'sci-fi',
    coverImage: 'https://m.media-amazon.com/images/I/81BWWw8+sCL._AC_UF1000,1000_QL80_.jpg',
    tags: ['Time Travel', 'Futurism', 'Classic'],
    vibe: 'Thought-Provoking & Epic',
    readCount: '11.7K',
    totalChapters: 16,
    readingLevel: 'Standard',
},
{
    id: 's-5',
    title: 'Twenty Thousand Leagues Under the Seas',
    author: 'Jules Verne',
    description: 'Captain Nemo and the Nautilus explore the oceans’ depths, encountering wonders and dangers beyond imagination.',
    theme: 'sci-fi',
    coverImage: 'https://www.hachettebookgroup.com/wp-content/uploads/2025/04/9781402776281.jpg',
    tags: ['Adventure', 'Ocean', 'Classic'],
    vibe: 'Epic & Exploratory',
    readCount: '13.4K',
    totalChapters: 22,
    readingLevel: 'Standard',
},
  {
    id: 's-6',
    title: 'The First Men in the Moon',
    author: 'H. G. Wells',
    description: 'A daring voyage to the Moon reveals a strange underground civilization of Selenites.',
    theme: 'sci-fi',
    coverImage: 'https://m.media-amazon.com/images/I/91OeflPZoZL._UF1000,1000_QL80_.jpg',
    tags: ['Moon', 'Adventure', 'Classic'],
    vibe: 'Adventurous & Mysterious',
    readCount: '10.2K',
    totalChapters: 18,
    readingLevel: 'Standard',
},
{
    id: 's-7',
    title: 'The Invisible Man',
    author: 'H. G. Wells',
    description: 'A scientist discovers the secret to invisibility, unleashing terror and moral questions.',
    theme: 'sci-fi',
    coverImage: 'https://cdn.kobo.com/book-images/fd82bd4a-81fa-4831-856f-4306d7b78e9f/1200/1200/False/the-invisible-man-279.jpg',
    tags: ['Science', 'Thriller', 'Classic'],
    vibe: 'Dark & Intriguing',
    readCount: '11.5K',
    totalChapters: 15,
    readingLevel: 'Standard',
},
{
    id: 's-8',
    title: 'The Island of Doctor Moreau',
    author: 'H. G. Wells',
    description: 'Shipwrecked on a mysterious island, a visitor discovers a mad scientist transforming animals into human-like creatures.',
    theme: 'sci-fi',
    coverImage: 'https://wyldblood.com/wp-content/uploads/2022/04/moreau-ebook-Oct-5.jpg',
    tags: ['Mad Science', 'Ethics', 'Classic'],
    vibe: 'Ominous & Thought-Provoking',
    readCount: '9.8K',
    totalChapters: 20,
    readingLevel: 'Standard',
},
{
    id: 's-9',
    title: 'Looking Backward: 2000-1887',
    author: 'Edward Bellamy',
    description: 'A man wakes up in the year 2000 to find a socialist utopia and a society transformed by technology.',
    theme: 'sci-fi',
    coverImage: 'https://m.media-amazon.com/images/I/91S+5ervWHL._UF1000,1000_QL80_.jpg',
    tags: ['Utopia', 'Society', 'Classic'],
    vibe: 'Visionary & Reflective',
    readCount: '8.5K',
    totalChapters: 24,
    readingLevel: 'Standard',
},
{
    id: 's-10',
    title: "Edison's Conquest of Mars",
    author: 'Garrett P. Serviss',
    description: 'Following the spirit of interplanetary adventure, Edison leads humanity against Martian invaders.',
    theme: 'sci-fi',
    coverImage: 'https://pictures.abebooks.com/isbn/9781532831843-us.jpg',
    tags: ['Adventure', 'Mars', 'Classic'],
    vibe: 'Exciting & Heroic',
    readCount: '7.9K',
    totalChapters: 16,
    readingLevel: 'Standard',
},
  {
    id: 'cr-2',
    title: 'Noir Shadows',
    author: 'Detective Vane',
    description: 'A private eye investigates a string of digital disappearances in Neo-London.',
    theme: 'crime',
    coverImage: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=800&auto=format&fit=crop',
    tags: ['Investigation', 'Rainy', 'Tech'],
    vibe: 'Dark & Gritty',
    readCount: '41.0K',
    totalChapters: 12,
    readingLevel: 'Standard',
  },
  {
    id: 'sh-1',
    title: 'A Scandal in Bohemia',
    author: 'Arthur Conan Doyle',
    description: 'The definitive abridged encounter between Sherlock Holmes and Irene Adler.',
    theme: 'crime',
    coverImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReN1wKKfDYGSR1OJcqMa9Jdif9e15JgTv85Q&s',
    tags: ['Sherlock', 'Detective', 'Mystery'],
    vibe: 'Intellectual & Tense',
    readCount: '34.5K',
    totalChapters: 8,
    readingLevel: 'Academic',
  },
  {
    id: 'sh-2',
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    description: 'Sherlock Holmes and Dr. Watson investigate a legendary curse on the moors of Devonshire.',
    theme: 'crime',
    coverImage: 'https://res.cloudinary.com/bloomsbury-atlas/image/upload/w_360,c_scale,dpr_1.5/jackets/9781847494962.jpg',
    tags: ['Sherlock', 'Detective', 'Mystery'],
    vibe: 'Suspenseful & Clever',
    readCount: '38.2K',
    totalChapters: 15,
    readingLevel: 'Academic',
  },
  {
    id: 'sh-3',
    title: 'A Study in Scarlet',
    author: 'Arthur Conan Doyle',
    description: 'The first appearance of Sherlock Holmes and Dr. Watson as they solve a mysterious murder in London.',
    theme: 'crime',
    coverImage: 'https://m.media-amazon.com/images/I/61+E1mduSuL._AC_UF1000,1000_QL80_.jpg',
    tags: ['Sherlock', 'Detective', 'Mystery'],
    vibe: 'Intriguing & Methodical',
    readCount: '36.0K',
    totalChapters: 12,
    readingLevel: 'Academic',
  },
  {
    id: 'sh-4',
    title: 'The Sign of Four',
    author: 'Arthur Conan Doyle',
    description: 'A complex treasure hunt leads Holmes and Watson into the depths of Victorian London’s criminal underworld.',
    theme: 'crime',
    coverImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVZ6Qtx_2TLI8sJOdNYWpkyVxnZ5ajbfQmkQ&s',
    tags: ['Sherlock', 'Detective', 'Mystery'],
    vibe: 'Clever & Tense',
    readCount: '32.5K',
    totalChapters: 14,
    readingLevel: 'Academic',
  },
  {
    id: 'sh-5',
    title: 'The Valley of Fear',
    author: 'Arthur Conan Doyle',
    description: 'Holmes unravels a deadly secret from an American mining town, hidden beneath layers of intrigue.',
    theme: 'crime',
    coverImage: 'https://res.cloudinary.com/bloomsbury-atlas/image/upload/w_360,c_scale,dpr_1.5/jackets/9781847498939.jpg',
    tags: ['Sherlock', 'Detective', 'Mystery'],
    vibe: 'Dark & Intelligent',
    readCount: '30.8K',
    totalChapters: 13,
    readingLevel: 'Academic',
  },
  {
    id: 'sh-6',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    description: 'A collection of twelve short stories featuring the iconic detective and his brilliant deductions.',
    theme: 'crime',
    coverImage: 'https://res.cloudinary.com/bloomsbury-atlas/image/upload/w_iw,h_ih/spreads/331113-3.jpg',
    tags: ['Sherlock', 'Detective', 'Short Stories'],
    vibe: 'Classic & Sharp',
    readCount: '40.1K',
    totalChapters: 12,
    readingLevel: 'Academic',
  },
  {
    id: 'sh-7',
    title: 'The Memoirs of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    description: 'Holmes recounts his most fascinating cases, blending suspense and logic with masterful storytelling.',
    theme: 'crime',
    coverImage: 'https://res.cloudinary.com/bloomsbury-atlas/image/upload/w_360,c_scale,dpr_1.5/jackets/9781847497444.jpg',
    tags: ['Sherlock', 'Detective', 'Mystery'],
    vibe: 'Mysterious & Elegant',
    readCount: '33.9K',
    totalChapters: 11,
    readingLevel: 'Academic',
  }
];

export const MOCK_USER: UserProfile = {
  username: "storyseeker_24",
  displayName: "Luna Nova",
  bio: "Collector of starlight and sci-fi tropes. Always reading, usually caffeinated. ☕✨",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luna",
  readingPreference: 'Standard',
  stats: {
    booksRead: 42,
    streak: 15,
    pagesTurned: "12.4K"
  },
  badges: [
    { id: 'b1', name: 'Night Owl', icon: '🦉', rarity: 'rare', unlockedAt: '2024-03-01' },
    { id: 'b2', name: 'Genre Hopper', icon: '🌈', rarity: 'legendary', unlockedAt: '2024-02-15' },
    { id: 'b3', name: 'First Choice', icon: '🎯', rarity: 'common', unlockedAt: '2024-01-20' },
  ],
  recentActivity: [
    "Finished reading 'Code: Genesis'",
    "Earned the 'Cyber Explorer' badge",
    "Shared their Classics shelf"
  ],
  completedBookIds: {}
};
